package modelo.entidad;

// Generated 25/02/2015 09:17:21 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "cargo", schema = "public")
public class Cargo implements java.io.Serializable {

	private int id;
	private Cargo cargo;
	private Empresa empresa;
	private String descripcion;
	private Integer tipo;
	private Set<UsuarioCargo> usuarioCargos = new HashSet<UsuarioCargo>(0);
	private Set<Cargo> cargos = new HashSet<Cargo>(0);
	private Set<Tarearepetitiva> tarearepetitivas = new HashSet<Tarearepetitiva>(
			0);
	private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

	public Cargo() {
	}

	public Cargo(int id) {
		this.id = id;
	}

	public Cargo(int id, Cargo cargo, Empresa empresa, String descripcion,
			Integer tipo, Set<UsuarioCargo> usuarioCargos, Set<Cargo> cargos,
			Set<Tarearepetitiva> tarearepetitivas, Set<Solicitud> solicituds) {
		this.id = id;
		this.cargo = cargo;
		this.empresa = empresa;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.usuarioCargos = usuarioCargos;
		this.cargos = cargos;
		this.tarearepetitivas = tarearepetitivas;
		this.solicituds = solicituds;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cargosupervisor")
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "tipo")
	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<UsuarioCargo> getUsuarioCargos() {
		return this.usuarioCargos;
	}

	public void setUsuarioCargos(Set<UsuarioCargo> usuarioCargos) {
		this.usuarioCargos = usuarioCargos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<Cargo> getCargos() {
		return this.cargos;
	}

	public void setCargos(Set<Cargo> cargos) {
		this.cargos = cargos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<Tarearepetitiva> getTarearepetitivas() {
		return this.tarearepetitivas;
	}

	public void setTarearepetitivas(Set<Tarearepetitiva> tarearepetitivas) {
		this.tarearepetitivas = tarearepetitivas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<Solicitud> getSolicituds() {
		return this.solicituds;
	}

	public void setSolicituds(Set<Solicitud> solicituds) {
		this.solicituds = solicituds;
	}

}
