package modelo.entidad;

// Generated 25/02/2015 09:17:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historicotarearepetitiva generated by hbm2java
 */
@Entity
@Table(name = "historicotarearepetitiva", schema = "public")
public class Historicotarearepetitiva implements java.io.Serializable {

	private int id;
	private Tarearepetitivaaux tarearepetitivaaux;
	private String razon;
	private Integer progreso;
	private Date fechainicio;
	private Date fechafin;
	private Date fechaculminado;

	public Historicotarearepetitiva() {
	}

	public Historicotarearepetitiva(int id) {
		this.id = id;
	}

	public Historicotarearepetitiva(int id,
			Tarearepetitivaaux tarearepetitivaaux, String razon,
			Integer progreso, Date fechainicio, Date fechafin,
			Date fechaculminado) {
		this.id = id;
		this.tarearepetitivaaux = tarearepetitivaaux;
		this.razon = razon;
		this.progreso = progreso;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.fechaculminado = fechaculminado;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tarearepetitivaaux")
	public Tarearepetitivaaux getTarearepetitivaaux() {
		return this.tarearepetitivaaux;
	}

	public void setTarearepetitivaaux(Tarearepetitivaaux tarearepetitivaaux) {
		this.tarearepetitivaaux = tarearepetitivaaux;
	}

	@Column(name = "razon")
	public String getRazon() {
		return this.razon;
	}

	public void setRazon(String razon) {
		this.razon = razon;
	}

	@Column(name = "progreso")
	public Integer getProgreso() {
		return this.progreso;
	}

	public void setProgreso(Integer progreso) {
		this.progreso = progreso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechainicio", length = 29)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", length = 29)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaculminado", length = 29)
	public Date getFechaculminado() {
		return this.fechaculminado;
	}

	public void setFechaculminado(Date fechaculminado) {
		this.fechaculminado = fechaculminado;
	}

}
