package modelo.entidad;

// Generated 25/02/2015 09:17:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tareaeventual generated by hbm2java
 */
@Entity
@Table(name = "tareaeventual", schema = "public")
public class Tareaeventual implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Integer avance;
	private Integer prioridad;
	private Date fechainicio;
	private Date fechafin;
	private Date fechaculminado;
	private Set<Historicotareaeventual> historicotareaeventuals = new HashSet<Historicotareaeventual>(
			0);

	public Tareaeventual() {
	}

	public Tareaeventual(int id) {
		this.id = id;
	}

	public Tareaeventual(int id, Usuario usuario, Integer avance,
			Integer prioridad, Date fechainicio, Date fechafin,
			Date fechaculminado,
			Set<Historicotareaeventual> historicotareaeventuals) {
		this.id = id;
		this.usuario = usuario;
		this.avance = avance;
		this.prioridad = prioridad;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.fechaculminado = fechaculminado;
		this.historicotareaeventuals = historicotareaeventuals;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuarioresponsable")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "avance")
	public Integer getAvance() {
		return this.avance;
	}

	public void setAvance(Integer avance) {
		this.avance = avance;
	}

	@Column(name = "prioridad")
	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechainicio", length = 29)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", length = 29)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaculminado", length = 29)
	public Date getFechaculminado() {
		return this.fechaculminado;
	}

	public void setFechaculminado(Date fechaculminado) {
		this.fechaculminado = fechaculminado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tareaeventual")
	public Set<Historicotareaeventual> getHistoricotareaeventuals() {
		return this.historicotareaeventuals;
	}

	public void setHistoricotareaeventuals(
			Set<Historicotareaeventual> historicotareaeventuals) {
		this.historicotareaeventuals = historicotareaeventuals;
	}

}
