package modelo.entidad;

// Generated 25/02/2015 09:17:21 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tarearepetitiva generated by hbm2java
 */
@Entity
@Table(name = "tarearepetitiva", schema = "public")
public class Tarearepetitiva implements java.io.Serializable {

	private int id;
	private Cargo cargo;
	private String descripcion;
	private Integer prioridad;
	private Set<Tarearepetitivaaux> tarearepetitivaauxes = new HashSet<Tarearepetitivaaux>(
			0);

	public Tarearepetitiva() {
	}

	public Tarearepetitiva(int id) {
		this.id = id;
	}

	public Tarearepetitiva(int id, Cargo cargo, String descripcion,
			Integer prioridad, Set<Tarearepetitivaaux> tarearepetitivaauxes) {
		this.id = id;
		this.cargo = cargo;
		this.descripcion = descripcion;
		this.prioridad = prioridad;
		this.tarearepetitivaauxes = tarearepetitivaauxes;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cargo")
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "prioridad")
	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarearepetitiva")
	public Set<Tarearepetitivaaux> getTarearepetitivaauxes() {
		return this.tarearepetitivaauxes;
	}

	public void setTarearepetitivaauxes(
			Set<Tarearepetitivaaux> tarearepetitivaauxes) {
		this.tarearepetitivaauxes = tarearepetitivaauxes;
	}

}
