package modelo.entidad;

// Generated 25/02/2015 09:17:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarearepetitivaaux generated by hbm2java
 */
@Entity
@Table(name = "tarearepetitivaaux", schema = "public")
public class Tarearepetitivaaux implements java.io.Serializable {

	private int id;
	private Tarearepetitiva tarearepetitiva;
	private Usuario usuario;
	private Integer progreso;
	private Integer avance;
	private Date fechaculminacion;
	private Date fechainicio;
	private Date fechafin;
	private Set<Historicotarearepetitiva> historicotarearepetitivas = new HashSet<Historicotarearepetitiva>(
			0);

	public Tarearepetitivaaux() {
	}

	public Tarearepetitivaaux(int id) {
		this.id = id;
	}

	public Tarearepetitivaaux(int id, Tarearepetitiva tarearepetitiva,
			Usuario usuario, Integer progreso, Integer avance,
			Date fechaculminacion, Date fechainicio, Date fechafin,
			Set<Historicotarearepetitiva> historicotarearepetitivas) {
		this.id = id;
		this.tarearepetitiva = tarearepetitiva;
		this.usuario = usuario;
		this.progreso = progreso;
		this.avance = avance;
		this.fechaculminacion = fechaculminacion;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.historicotarearepetitivas = historicotarearepetitivas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tarearepetitiva")
	public Tarearepetitiva getTarearepetitiva() {
		return this.tarearepetitiva;
	}

	public void setTarearepetitiva(Tarearepetitiva tarearepetitiva) {
		this.tarearepetitiva = tarearepetitiva;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "progreso")
	public Integer getProgreso() {
		return this.progreso;
	}

	public void setProgreso(Integer progreso) {
		this.progreso = progreso;
	}

	@Column(name = "avance")
	public Integer getAvance() {
		return this.avance;
	}

	public void setAvance(Integer avance) {
		this.avance = avance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaculminacion", length = 29)
	public Date getFechaculminacion() {
		return this.fechaculminacion;
	}

	public void setFechaculminacion(Date fechaculminacion) {
		this.fechaculminacion = fechaculminacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechainicio", length = 35)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", length = 35)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarearepetitivaaux")
	public Set<Historicotarearepetitiva> getHistoricotarearepetitivas() {
		return this.historicotarearepetitivas;
	}

	public void setHistoricotarearepetitivas(
			Set<Historicotarearepetitiva> historicotarearepetitivas) {
		this.historicotarearepetitivas = historicotarearepetitivas;
	}

}
