package modelo.entidad;

// Generated 25/02/2015 09:17:21 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "public")
public class Usuario implements java.io.Serializable {

	private int id;
	private String cedula;
	private String nombre;
	private String telefono;
	private String direccion;
	private String usuario;
	private String clave;
	private Integer privilegio;
	private Set<Tareaeventual> tareaeventuals = new HashSet<Tareaeventual>(0);
	private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
	private Set<Tarearepetitivaaux> tarearepetitivaauxes = new HashSet<Tarearepetitivaaux>(
			0);
	private Set<UsuarioEmpresa> usuarioEmpresas = new HashSet<UsuarioEmpresa>(0);
	private Set<UsuarioCargo> usuarioCargos = new HashSet<UsuarioCargo>(0);

	public Usuario() {
	}

	public Usuario(int id) {
		this.id = id;
	}

	public Usuario(int id, String cedula, String nombre, String telefono,
			String direccion, String usuario, String clave, Integer privilegio,
			Set<Tareaeventual> tareaeventuals, Set<Solicitud> solicituds,
			Set<Tarearepetitivaaux> tarearepetitivaauxes,
			Set<UsuarioEmpresa> usuarioEmpresas, Set<UsuarioCargo> usuarioCargos) {
		this.id = id;
		this.cedula = cedula;
		this.nombre = nombre;
		this.telefono = telefono;
		this.direccion = direccion;
		this.usuario = usuario;
		this.clave = clave;
		this.privilegio = privilegio;
		this.tareaeventuals = tareaeventuals;
		this.solicituds = solicituds;
		this.tarearepetitivaauxes = tarearepetitivaauxes;
		this.usuarioEmpresas = usuarioEmpresas;
		this.usuarioCargos = usuarioCargos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cedula")
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "usuario")
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "clave")
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "privilegio")
	public Integer getPrivilegio() {
		return this.privilegio;
	}

	public void setPrivilegio(Integer privilegio) {
		this.privilegio = privilegio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Tareaeventual> getTareaeventuals() {
		return this.tareaeventuals;
	}

	public void setTareaeventuals(Set<Tareaeventual> tareaeventuals) {
		this.tareaeventuals = tareaeventuals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Solicitud> getSolicituds() {
		return this.solicituds;
	}

	public void setSolicituds(Set<Solicitud> solicituds) {
		this.solicituds = solicituds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Tarearepetitivaaux> getTarearepetitivaauxes() {
		return this.tarearepetitivaauxes;
	}

	public void setTarearepetitivaauxes(
			Set<Tarearepetitivaaux> tarearepetitivaauxes) {
		this.tarearepetitivaauxes = tarearepetitivaauxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioEmpresa> getUsuarioEmpresas() {
		return this.usuarioEmpresas;
	}

	public void setUsuarioEmpresas(Set<UsuarioEmpresa> usuarioEmpresas) {
		this.usuarioEmpresas = usuarioEmpresas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioCargo> getUsuarioCargos() {
		return this.usuarioCargos;
	}

	public void setUsuarioCargos(Set<UsuarioCargo> usuarioCargos) {
		this.usuarioCargos = usuarioCargos;
	}

}
