package modelo.entidad;

// Generated 25/02/2015 09:17:21 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioEmpresaId generated by hbm2java
 */
@Embeddable
public class UsuarioEmpresaId implements java.io.Serializable {

	private int idUsuario;
	private int idEmpresa;

	public UsuarioEmpresaId() {
	}

	public UsuarioEmpresaId(int idUsuario, int idEmpresa) {
		this.idUsuario = idUsuario;
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "id_usuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_empresa", nullable = false)
	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioEmpresaId))
			return false;
		UsuarioEmpresaId castOther = (UsuarioEmpresaId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdEmpresa() == castOther.getIdEmpresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdEmpresa();
		return result;
	}

}
